USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make
PB_EXTRA_ARGS+= --sign "Graham Pugh"
PB_EXTRA_ARGS+= --info "./PackageInfo"

TITLE=Munki-UOB-Uninstall
PACKAGE_NAME=${TITLE}
REVERSE_DOMAIN=uk.ac.bris
PAYLOAD=\
  pack-script-postinstall
