#!/bin/bash

# This postinstall script runs all the scripts that the package placed into the target
# Library, and then deletes the folder that was previously created to remove the cruft

log() {
  echo "${@}" 2>&1 
  logger -t Munki installer "${@}"
}

# Now Let's install Munki!
sudo installer -pkg /Library/Management/munki-with-config/installers/munki-latest.pkg -target /

# Finally let's run the config script, and clear up after ourselves
sudo bash /Library/Management/munki-with-config/install_scripts/munki_config.sh
sudo rm -rf /Library/Management/munki-with-config
exit 0